server:
  port: 9001

spring:
  application:
    name: CONSTELLATION-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
#    instance:
#      hostname: localhost