# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Service Registry
      run: mvn -f ./service-registry/service-registry/pom.xml package
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ./service-registry/service-registry/target/*.jar
    - name: Build Satellite Service
      run: mvn -f ./satellite-service/satellite-service/pom.xml clean verify
    - name: Build Constellation Service
      run: mvn -f ./constellation-service/constellation-service/pom.xml clean verify
  deploy: 
    runs-on: ubuntu-latest  
    needs: build 
    name: Build Docker container 
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker container
      run: docker-compose up      
    - name: Build Docker container
      run: docker-compose down
